### ISSUE TITLE
The project does not work on UE4.24

### ISSUE THREAD

**Issue by paliacci** [RuWhyNot/rubiks-cube-ue4#1]
Error message:
Error: CDO Constructor (RubiksBlock_Standart): Failed to find StaticMesh‘/Game/Cube/Block/Block_BlackPlasic.Block_BlackPlasic’

**Comment by gameraccoon** [comment]
That looks a lot like the project was cloned without LFS.
At least that the only way how I can reproduce the issue.
Will add the info about LFS to the README.
